# SSGangSMP - Configuration file
# version 1.0.0_dev
# (c) SSGang Developers 2022

# The language used in the plugin.
language: en

# Discord bot token
botToken: ''

# Channel where bot will listen for message and send new message to it
chatChannelId: ''