on:
  push:
    # branches: [ main ]
    branches-ignore: [ '**' ] # Temporarily disable this action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Gradle
        run: |
          chmod +x gradlew

      - name: Generate jar file
        run: |
          gradlew shadowJar

      - name: Moving generated artifacts
        run: |
          mkdir staging
          cp build/libs/*.jar staging