name: amogsus

on:
  push:
    # branches: [ main ]
    branches-ignore: [ '**' ] # Temporarily disables this action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Gradle
        run: |
          chmod +x gradlew

      - name: Generate jar file
        run: |
          gradlew shadowJar

      - name: Moving generated artifacts
        run: |
          mkdir staging
          cp build/libs/*.jar staging

      - name: Run NodeJS script
        uses: actions/setup-node@v3
        run: |
          cd scripts
          npm install
          node . uploadJar ${{ secrets.ftp_host }} ${{ secrets.ftp_port }} ${{ secrets.ftp_user }} ${{ secrets.ftp_password }}
