name: amogsus

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Prepare Gradle
        run: |
          chmod +x gradlew
      - name: Gradle build
        uses: gradle/gradle-build-action@v2.2.0-beta.1
        with:
          arguments: build
      - name: Moving generated artifacts
        run: |
          mkdir staging
          cp build/libs/*.jar staging
      - name: Uploading artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: BlockArtOnline
          path: staging
