name: Upload jar to server

on:
  workflow_dispatch:
  push:
    # branches: [ main ]
    branches-ignore: [ '**' ] # Temporarily disables this action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare Gradle
        run: |
          chmod +x gradlew

      - name: Generate jar file
        run: |
          gradlew shadowJar

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Upload jar to server
        run: |
          cd /scripts/uploadJar
          npm i -y
          node . ${{ secrets.sftp_host }} ${{ secrets.sftp_port }} ${{ secrets.sftp_user }} ${{ secrets.sftp_password }}